---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-linters
    post:
      jobs:
        - publish-stx-specs
